# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lambe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lambe

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'lambe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lambeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'lambe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lambe-tvOS

  target 'lambe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
